# Generated by Django 6.0.4 on 2026-06-28 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0003_exam_semester'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='administration.course')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.semester')),
            ],
        ),
        migrations.CreateModel(
            name='FeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.PositiveIntegerField()),
                ('payment_date', models.DateField()),
                ('transactionid', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(choices=[('PAID', 'paid'), ('PENDING', 'pending'), ('PARTIAL', 'partial')], max_length=10)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
                ('feestructure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountant.feestructure')),
            ],
        ),
    ]
